# Sets up the Althea info server plus an nginx server to host the frontend

- name: Install Althea Info server
  hosts: althea_info_server
  user: root
  roles:
    - install-deps
    - setup-nginx
    - setup-info-server

